on:
  push:
    branches:
      - main
    paths:
      - "docs/**/*"
      - .github/workflows/quartodoc.yaml
  workflow_dispatch:

name: quartodoc.yaml

permissions: read-all
env:
  UV_VERSION: "0.7.x"
  PYTHON_VERSION: 3.13
  QUARTO_VERSION: 1.7.31

jobs:
  docs-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # full history needed for correct versioning of py pkg

    - name: ğŸ”µ Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: ${{ env.QUARTO_VERSION }}

    - name: ğŸš€ Install uv
      uses: astral-sh/setup-uv@v6.1.0
      with:
        version: ${{ env.UV_VERSION }}

    - name: ğŸ Set up Python ${{ env.PYTHON_VERSION }}
      run: uv python install ${{ env.PYTHON_VERSION }}

    - name: ğŸ“¦ Install shinychat and dependencies
      run: uv sync --python ${{ env.PYTHON_VERSION }} --all-extras

    - name: ğŸ”Œ Activate venv
      run: |
        source .venv/bin/activate
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

    - name: ğŸ­ Update Python docs
      run: |
        make py-docs-api
        quarto render pkg-py/docs

    - name: ğŸš¢ Deploy to GitHub pages
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        clean: false
        folder: docs
        branch: gh-pages
